export { DashboardPage } from './Dashboard'
export { default as NovaBobinaPage } from './nova-bobina'
export { NovoPedidoPage } from './NovoPedido'
export { PedidosPage } from './Pedidos'
export { GestaoMaquinasPage } from './GestaoMaquinasPage'
