export { DashboardPage } from './Dashboard'
export { NovaBobinaPage } from './nova-bobina/NovaBobinaPage'
export { NovoPedidoPage } from './NovoPedido'
export { PedidosPage } from './Pedidos'
export { GestaoMaquinasPage } from './GestaoMaquinasPage'
